name = "granja-vincwill-backend"
main = "src/index.js"
compatibility_date = "2025-10-17"
compatibility_flags = ["nodejs_compat"]

[vars]
DATABASE_URL = "postgresql://neondb_owner:npg_z3WSXD5dPTGm@ep-broad-sun-ac5euzsd-pooler.sa-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require"
JWT_SECRET = "PYV4qzOP1JIuK/oiIqxr3D/ipaJqQbuhK3KxidHkI4o="
PORT = "3000"