name = "granja-vincwill-backend"
main = "src/index.js"
compatibility_date = "2025-10-28"

[vars]
JWT_SECRET = "egY4f4-a810wD1i6D2V5kscW32223A6Knm6aGkyXu3tSc="
PORT = "3000"

[dev]
ip = "0.0.0.0"
port = 8787
local_protocol = "http"

[node_compat]
enabled = true